In [15]:
#import packages
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
iris_df = pd.read_csv('/Users/nickthomas/git/PythonProjects/frameworks/logistic_regression/IRIS.csv')
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [17]:
print("Shape of the data frame: ",iris_df.shape)
print("Total null values: ",iris_df.isna().sum().sum())
print("Duplicate values: ",iris_df.duplicated().sum() )


Shape of the data frame:  (150, 5)
Total null values:  0
Duplicate values:  3


In [18]:
iris_df.drop_duplicates(inplace=True)
print("Shape of the data frame: ",iris_df.shape)
print("\n")
print("Species categories with its count \n",iris_df["species"].value_counts())

Shape of the data frame:  (147, 5)


Species categories with its count 
 species
Iris-versicolor    50
Iris-virginica     49
Iris-setosa        48
Name: count, dtype: int64


In [19]:
iris_df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    147.000000   147.000000    147.000000   147.000000
mean       5.856463     3.055782      3.780272     1.208844
std        0.829100     0.437009      1.759111     0.757874
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [20]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
iris_df["species"]=label_encoder.fit_transform(iris_df["species"])
print(iris_df.head(10))
print("\n")
print(iris_df["species"].value_counts())

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0
5           5.4          3.9           1.7          0.4        0
6           4.6          3.4           1.4          0.3        0
7           5.0          3.4           1.5          0.2        0
8           4.4          2.9           1.4          0.2        0
9           4.9          3.1           1.5          0.1        0


species
1    50
2    49
0    48
Name: count, dtype: int64


In [21]:
X=iris_df.drop(["species"],axis=1)
Y=iris_df["species"]

In [22]:
from sklearn.model_selection import train_test_split
X_train1,X_test1,Y_train1,Y_test1=train_test_split(X,Y,test_size=0.2,random_state=3)

In [23]:
from sklearn.linear_model import LogisticRegression
logistic_reg=LogisticRegression()

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
logistic_reg.fit(X_train1,Y_train1)
predicted_result1=logistic_reg.predict(X_test1)

In [25]:
predicted_result1

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 1, 2, 2, 1, 0,
       2, 0, 0, 1, 2, 0, 1, 1])

In [26]:
print("Accuracy Score: ",accuracy_score(Y_test1, predicted_result1))

print("Confusion Matrix:\n ",confusion_matrix(Y_test1, predicted_result1))

print("Classification Report:\n ",classification_report(Y_test1, predicted_result1))

Accuracy Score:  0.9666666666666667
Confusion Matrix:
  [[12  0  0]
 [ 0  9  1]
 [ 0  0  8]]
Classification Report:
                precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.90      0.95        10
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

