In [1]:
# DataFrame
import pandas as pd
import numpy as np

# Matplot
import matplotlib.pyplot as plt
%matplotlib inline

import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 



In [2]:
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nickthomas/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [4]:
data=pd.read_csv('/Users/nickthomas/git/PythonProjects/sentimentAnalysis/twitterExample/training.1600000.processed.noemoticon.csv',encoding='ISO-8859-1', header = None)

In [5]:
data.head()

0           1                             2         3                4  \
0  0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  _TheSpecialOne_   
1  0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY    scotthamilton   
2  0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY         mattycus   
3  0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          ElleCTF   
4  0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY           Karoli   

                                                   5  
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1  is upset that he can't update his Facebook by ...  
2  @Kenichan I dived many times for the ball. Man...  
3    my whole body feels itchy and like its on fire   
4  @nationwideclass no, it's not behaving at all....

In [6]:
data.shape

(1600000, 6)

In [7]:
data = data.sample(n=100000, random_state=10)

In [8]:
cols=['target','id','date','flag','user','text']

data.columns = cols

data.head()

data['target'].value_counts()

target
0    50016
4    49984
Name: count, dtype: int64

In [9]:
#replace the 4 with 1 in the DF
data.replace({"target":{4:1}}, inplace=True)

In [ ]:
# port_stem=PorterStemmer()

In [ ]:
# def stemming(content):
#     stemmed_content=re.sub('[^a-zA-Z]'," ",content)
#     stemmed_content=stemmed_content.lower()
#     stemmed_content=stemmed_content.split()
#     stemmed_content=[port_stem.stem(words) for words in stemmed_content if not words in stopwords.words('english')]
#     stemmed_content=" ".join(stemmed_content)
#     return stemmed_content   

In [ ]:
# from tqdm import tqdm

# # Ensure that tqdm works with Pandas apply method
# tqdm.pandas()

# # Use tqdm with apply to see progress
# data['stemmed_content'] = data['text'].progress_apply(stemming)

100%|██████████| 100000/100000 [05:24<00:00, 308.55it/s]


In [10]:
data.head()

target          id                          date      flag  \
685610        0  2250819430  Sat Jun 20 01:34:59 PDT 2009  NO_QUERY   
446784        0  2068515884  Sun Jun 07 14:12:53 PDT 2009  NO_QUERY   
1231978       1  1991871464  Mon Jun 01 07:48:38 PDT 2009  NO_QUERY   
1496263       1  2070090087  Sun Jun 07 17:04:40 PDT 2009  NO_QUERY   
944257        1  1795457800  Thu May 14 07:48:29 PDT 2009  NO_QUERY   

                   user                                               text  
685610     The_Khristos  @MrDAprano, honnestly I'm not going to miss th...  
446784            teale  Tired after spending a restless night with Tie...  
1231978      jenjeahaly  @bradgallaway Yup popiscle  Not sure if you've...  
1496263  fashinator1985      @candydiaz LOL save a lil arse for me candy!   
944257           krrley  @StephanieFizer No problem!! Your stuff is so ...

In [11]:
# x=data['stemmed_content'].values
x=data['text'].values
y=data['target'].values

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [12]:
print(x_train.shape)

(80000,)


In [13]:
vectorizer =TfidfVectorizer()
x_train = vectorizer.fit_transform(x_train)
x_test = vectorizer.transform(x_test)

In [14]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [15]:
prediction=model.predict(x_train)
accuracy_X=accuracy_score(y_train,prediction)

In [16]:
print("accuracy score for train data :",accuracy_X)

accuracy score for train data : 0.8388875


In [37]:
prediction=model.predict(x_test)
accuracy_Y=accuracy_score(y_test,prediction)

In [39]:
print('accuracy score for test data',accuracy_Y)

accuracy score for test data 0.7822


In [19]:
import pickle as pkl

In [20]:
file = 'senti_analysis_ex.pkl'
pkl.dump('model',open(file,'wb'))

In [21]:
loaded_model=pkl.load(open("/Users/nickthomas/git/PythonProjects/sentimentAnalysis/twitterExample/senti_analysis_ex.pkl",'rb'))

In [22]:
x_new=x_test[200]
print(y_test[200])
prediction=model.predict(x_new)
if(prediction[0]==0):
    print("negative")
else:
    print("positive")

0
negative


In [23]:
dense_x_test = x_test.toarray()
print(dense_x_test)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [24]:
# Set the maximum column width to None to avoid truncating long strings
pd.set_option('display.max_colwidth', None)

In [25]:
data['text']

685610               @MrDAprano, honnestly I'm not going to miss the Janitor as the show was seriously loseing its tracks in seasons 6, 7 and even 8 
446784                    Tired after spending a restless night with Tiernan.  Off to the doctors with him today, I suspect he has an ear infection. 
1231978    @bradgallaway Yup popiscle  Not sure if you've got strawberry splits there, but they're strawberry ice withvanilla ice cream in the middle
1496263                                                                                                 @candydiaz LOL save a lil arse for me candy! 
944257                                     @StephanieFizer No problem!! Your stuff is so cute. Can't wait to see the mini cards you're making for me 
                                                                              ...                                                                    
600988                                   Not going to make it to the #lancup . Thought I'd update my

In [26]:
test = ['@MrDAprano, honnestly I am not going to miss the Janitor as the show was seriously loseing its tracks in seasons 6, 7 and even 8']
test_transformed = vectorizer.transform(test)

In [27]:
test_transformed

<1x82612 sparse matrix of type '<class 'numpy.float64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [28]:
prediction = model.predict(test_transformed)

if(prediction[0]==0):
    print("negative")
else:
    print("positive")

negative


In [60]:
test2 = ['Sherrone Moore is such a great football coach']
test2_transformed = vectorizer.transform(test2)

In [ ]:
test2_transformed

<1x82612 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [62]:
prediction2 = model.predict(test2_transformed)

if(prediction2[0]==0):
    print("negative")
else:
    print("positive")

positive
